name: Tests Windows
on: [push]
jobs:
  Test:
    runs-on: windows-latest
    steps:
      - name: Install cargo
        run: |
          curl -O https://static.rust-lang.org/rustup/dist/x86_64-pc-windows-msvc/rustup-init.exe
          ./rustup-init.exe
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run tests
        run: |
          cd  ${{ github.workspace }}
          cargo test
