[package]
name = "save_reddit_post"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest="*"
dotenv="*"
tokio = { version="1", features = ["full"]}
json = "*"
serde_json = "*"
